
wr.FIELD_TYPE_INT = 1;
wr.FIELD_TYPE_FLOAT = 2;
wr.FIELD_TYPE_STRING = 3;
wr.FIELD_TYPE_DATE = 4;
wr.FIELD_TYPE_TDATE = 5;
wr.FIELD_TYPE_FILE = 6;
wr.FIELD_TYPE_IMAGE = 7;
wr.FIELD_TYPE_TAGS = 8;
wr.FIELD_TYPE_SLUG = 9;
